
# Pest monitoring and surveillance

## Pest Monitoring  
Monitoring phytophagous insects and their natural
enemies is a fundamental tool in IPM -- for taking management decision

### Monitoring -- objectives

-   estimation of changes in insect distribution and abundance

-   information about insects, life history

### Pest Surveillance

-   Refers to the constant watch on the population dynamics of pests,
    its incidence and damage on each crop at fixed intervals to forewarn
    the farmers to take up timely crop protection measures.

-   Three basic components of pest surveillance

-   Determination of

-   the level of incidence of the pest species

-   the loss caused by the incidence

-   the economic benefits, the control will provide

-   Monitoring no: and life stages of pest whereas surveillance include
    assessment of loss and economic benefits also.

#### Objectives of Pest Surveillance  

-   to know existing and new pest species

-   to assess pest population and damage at different growth stage of
    crop

-   to study the influence of weather parameters on pest

-   to study changing pest status (Minor to major)

-   to assess natural enemies and their influence on pests

-   to study the effect of new cropping pattern and varieties on pest

#### The reports involved  

*There are three kinds of reports involved in surveillance programme*

##### White card report or Normal report  

-   This is a weekly report in which the pest and disease situations are
    reported regularly

##### Yellow card

-   This is a special reporting system wherever pest or disease is
    noticed at 50% of the economic threshold level but still not
    attained ETL status. The information is immediately passed on for
    alerting the Joint Director of Agriculture (T&V), his subject matter
    specialists, and the scientists.

##### Redcard
    This reporting system is adopted when a pest or a disease has
    reached the critical economic threshold level where immediate action
    programme has to be launched for controlling the pest or disease.

## Pest Forecasting

-   Forecasting of pest incidence or outbreak based on information
    obtained from pest surveillance.

> Uses

-   \- Predicting pest outbreak which needs control measure

-   \- Suitable stage at which control measure gives maximum protection

### Two types of pest forecasting

#### Short term forecasting  
Based on 1 or 2 seasons

#### Long term forecasting  
Based on effect of weather parameters on pest

## Survey
Survey is conducted to study the abundance of a pest species

### Types of survey

Two types of survey, Roving survey and fixed plot survey

#### Roving survey  
Assessment of pest population/damage from randomly selected spots representing larger area - Large area surveyed in short period - Provides information on pest level over large area.

#### Fixed plot survey  
Assessment of pest population/damage from a fixed plot selected in a field. The data on pest population/damage is recorded periodically from sowing till harvest.  
-   e.g. 1 sq.m. plots randomly selected from 5 spots in one acre of
    crop area in case of rice. From each plot 10 plant selected at
    random. Total tillers and tillers affected by stem borer in these 10
    plants counted. Total leaves and number affected by leaf folder
    observed. Damage expressed as per cent damaged tillers or leaves.
    Population of BPH from all tillers in 10 plants is observed and
    expressed as number/tiller

#### Qualitative survey  
aims at pest detection, employed with newly
    introduced pests and often precedes quantitative survey.It gives
    non-numerical values (abundant, rare, present, absent) in relation
    to pest density.

#### Quantitative survey  
to define numerically the abundance of an
    insect population in time and space; useful for future population
    detection and assessment of damage potential.

## Sampling insect populations:Why?  

> In quantitative survey ,a count of insects is required.

-   Due to large number and/or secretive nature ,it is not possible to
    count each and every individual in a population.Hence more efficient
    method is by sampling.

-   Randomization and the choice of sampling unit are the fundamentals
    of sampling.

-   The total number of samples to be taken depends upon the degree of
    precision required

### Sampling unit
> Sampling unit is a portion of the habitat from which insect counts are
> to be made

-   e.g. a plant, branch, leaves or fruiting bodies, a clump, a micro
    plot of 1 m^2^, etc.

-   Sampling unit must be distinct and should not overlap.

-   **Sample:** A group of sampling units from which an estimate is
    made.\
    \
    **Sampling technique: **It is the method used to collect information
    from a single sampling unit.\
    \
    **Sampling programme:** Sampling programme is the procedure that
    employs the sampling technique to obtain sample and make a density
    estimate

## Sampling programmes
### Extensive programmes
> Conducted over a large area to determine information like species
> distribution, status of injurious insect stages.

-   Usually a single insect stage is sampled.

-   Only one or few samples are taken per season.

-   Only moderate levels of precision are required and emphasis on low
    cost.

### Intensive programmes
> Conducted as part of research in population ecology.

-   Here sampling is done frequently, in a small area

-   All or most stages in the life cycle are sampled

-   High degree of precision in sought

## Methods of sampling

### In situ  
counts - Visual observation on number of insects on
    plant canopy (either entire plot or randomly selected plot)

### Knock down  
Collecting insects from an area by removing from
    crop and counting

### Netting  
Use of sweep net for hoppers, odonates, grasshopper

### Narcotised collection  
Quick moving insects anaesthetised and
    counted

### Trapping  

-   Light trap - Phototropic insects**

-   Pheromone trap - Species specific

-   Sticky trap - Sucking insects

-   Bait trap - Sorghum shootfly - Fishmeal trap

-   Emergence trap - to capture insects that live below ground or under water. Usually such traps take advantage of the insects tendency to move to light, and have a capturing or killing mechanism at the top
    of the trap.

### Mark, release and recapture technique (MRR)

-   ***In situ* counts**

-   Direct observation and counts of an insect within its habitat (no
    special equipment is needed).

-   If insect numbers are low and plants are small all insects on the
    plant may be counted. If organisms are too scattered to be counted,
    a selected number of organisms within an area may be sampled.

-   An equipment such as a piece of square metal can be used to assist
    with the counting. For large plants, known numbers of leaves, stems,
    flowers, budsor pods are counted.

> **The most widely used method of sampling plants**

### Knock down sampling

-   Insects are removed from the habitat by chemicals, heat or jarring

#### Heating  
is used when sampling insects from organic matter. A
    standard berlesefunnel, that heats the sample. Insects move out of
    the plant material falling through the funnel and are collected in a
    jar placed at the bottom of the funnel.

-   It only captures species that are mobile

#### Netting  
A sweep-net is swung into the plant canopy and after a
    prescribed number of swings, the plant debris are moved and the
    number of insects caught are counted.

-   It is inexpensive and adequate sample size can be obtained by
    increasing the number of swings.

#### Trapping  
One of the most important techniques used for
    monitoring insect abundance and behavior. Traps are left in the
    field for a period of time and then insect numbers are counted.

## Types of traps

-   **Traps are either attractive or passive**.

### Attractive traps  
rely on visual or chemical stimulus to lure
    insects to them.  
#### Visual trap  
relies on light, shape, or color

-   The light trap is the most widely used visual trap for
    Lepidopteran(Moths) and Dipteran(mosquitoes) insects.

-   Many insects are attracted by short wavelengths of the light
    spectrum

### Passive Trap  

Passive traps catch insects accidentally.

#### Pitfall trap  
A trap designed for catching ground crawling insects.
    Usually a container is buried in the ground into which insects fall

#### Malaise trap  
It is basically a tent, which is open at the front. The
    roof converge into a collecting jar. These traps are useful in
    collecting aphids and leafhoppers.

## Population estimates
### Absolute estimates

-   Absolute estimates (number per ground surface area e.g. per hectare
    or acre or m^2^)

-   Population intensity (per habitat unit e.g. leaf, plant, etc)

-   Basic population estimates (intermediate between above two e.g. per
    5 cm of stem)

### Relative estimates  
Don't give definite number per unit area
-   Population indices (insects themselves are not counted but their
    products)

## Terms in sampling
### Absolute sampling  
To count all the pests occurring in a plot**

### Relative sampling  
To measure pest in terms of some values which
    can be compared over time and space e.g. Light trap catch, Pheromone
    trap

### Absolute Sample

-   is fairly accurate and is a good system to use when gathering
    information about a new pest that has invaded an area.

-   very time consuming

### Relative Sample  
Count a subset of the entire population

**[Advantage]{.ul}**

-   [-]{.ul}not very time consuming

-   -Disadvantage

-   -reliability varies

## Criteria of estimates

-   The estimates must be evaluated for:

### Fidelity  
Accuracy with which estimates follow the actual number in
    the population.

### Precision  
It is the reproducibility of the results and measures the
    degree of error

### Cost  
Cost is very important. Any estimates having great fidelity
    and precision will be of no use until and unless it is cost effective

## Parameters of sampling programme

-   Insect stage to be sampled

-   Number of sampling units

-   Time of sample

-   Pattern of sampling

-   Types of sampling

## Sampling unit

-   The size should be such that every unit of the universe should have
    the chance of selection.

-   Sampling unit must be easily described in the field

-   Sampling unit should be of such that it provides a reasonable
    balance between precision and cost

## Factors affecting sampling accuracy

-   Field size and shape

-   Variation between individuals and differences in perception

-   Consistency of sampling methods

-   The numbers of samples taken

## Components of a sampling plan

-   • Sample universe (area of concern)

-   • Timing (seasonality and developmental stage)

-   • Sample unit (actual area sampled)

-   • Spatial distribution (aggregated or clumped, random, uniform)

-   • Sample size

## Types of sampling

### Random sampling  
Random sampling is a part of the sampling
    technique in which each sample has an equal probability of being
    chosen. A sample chosen randomly is meant to be an unbiased
    representation of the total population.

### Stratified random sampling 
It is a method of sampling that involves
    the division of a population into smaller sub-groups known as
    strata.

### Systematic sampling  
sample members from a larger population are
    selected according to a random starting point but with a fixed,
    periodic interval. This interval, called the sampling interval, is
    calculated by dividing the population size by the desired sample
    size.

### Sequential sampling 
In sequential sampling the researcher picks a single or a group of
    subjects in a given time interval, conducts his study, analyzes the
    results then picks another group of subjects if needed and so on
